theme: minima

title: Tim Miller, GVE TSA Data Center
author:
  name: Tim Miller

description: GitHub blog posts and repositories for projects related to work at Cisco as a Data Center Technical Solutions Architect in Global Virtual Engineering.

show_download: false
show_excerpts: true

minima:
  social_links:
    github: gve-vse-tim

plugins:
 - jekyll-seo-tag

