theme: jekyll-theme-minimal
title: Tim Miller, GVE VCSE Data Center
description: GitHub Repos for projects related to work at Cisco as a Data Center Virtual Consulting Systems Engineer in Global Virtual Engineering.
show_download: "false"
